users:
  - username: username
    password: password
    active: true
  - username: username1
    password: password1
    active: true
  - username: username2
    password: password2
    active: false
fqdns:
  - addr: www.google.es
    active: true
  - addr: www.google.com
    active: true


